#!/usr/bin/env bash
# This script checks if the '/etc/passwd' file exists and displays username, user id, and home directory path for each user

passwd_file="/etc/passwd"

if [ -e "$passwd_file" ]; then
    echo "school file exists"
    
    if [ -s "$passwd_file" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    
    if [ -f "$passwd_file" ]; then
        echo "school is a regular file"
    fi
    
    # Reading '/etc/passwd' line by line
    while IFS=: read -r username _ uid _ _ homedir _; do
        # Display username, uid, and homedir
        echo "$username:$uid:$homedir"
    done < "$passwd_file"
else
    echo "school file does not exist"
fi
