#!/bin/bash

while IFS=: read -r username password uid gid gecos home shell
do
  if [ -z "$shell" ]; then
    shell="."
  fi
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd
