#!/usr/bin/env bash
# This script loops from 1 to 20 using a while loop and displays:
# - "bad luck from China" on the 4th iteration
# - "bad luck from Japan" on the 9th iteration
# - "bad luck from Italy" on the 17th iteration
# - The number itself on all other iterations

count=1

while [ "$count" -le 20 ]; do
  echo "$count"
  
  case "$count" in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
    *)
      # Do nothing for other numbers
      ;;
  esac
  
  count=$((count + 1))
done
